# asyncio --- 异步 I/O


> 踩坑 进行总结。tmd。只记录最新版的Python能够使用的协程方式。



## 对象


### Eventloop
Eventloop可以说是asyncio应用的核心，是中央总控。Eventloop实例提供了注册、取消和执行任务和回调的方法。

把一些异步函数(就是任务，Task，一会就会说到)注册到这个事件循环上，事件循环会循环执行这些函数(但同时只能执行一个)，当执行到某个函数时，如果它正在等待I/O返回，事件循环会暂停它的执行去执行其他的函数；当某个函数完成I/O后会恢复，下次循环到它的时候继续执行。因此，这些异步函数可以协同(Cooperative)运行：这就是事件循环的目标。



### Coroutine
协程(Coroutine)本质上是一个函数，特点是在代码块中可以将执行权交给其他协程




```
❯ cat coro1.py
import asyncio


async def a():
    print('Suspending a')
    await asyncio.sleep(0)
    print('Resuming a')


async def b():
    print('In b')


async def main():
    await asyncio.gather(a(), b())


if __name__ == '__main__':
    asyncio.run(main())
```
1. 协程要用async def声明，Python 3.5时的装饰器写法已经过时，我就不列出来了。
2. asyncio.gather用来并发运行任务，在这里表示协同的执行a和b2个协程
3. 在协程a中，有一句await asyncio.sleep(0)，await表示调用协程，sleep 0并不会真的sleep（因为时间为0），但是却可以把控制权交出去了。
4. **非常关键：**只要在await操作的时候。才会将执行权交给其他协程。否则会一直执行该协程。



### Future 
它代表了一个「未来」对象，异步操作结束后会把最终结果设置到这个Future对象上。Future是对协程的封装，不过日常开发基本是不需要直接用这个底层Future类的。

可以对这个Future实例添加完成后的回调(add_done_callback)、取消任务(cancel)、设置最终结果(set_result)、设置异常(如果有的话，set_exception)等。现在我们让Future完成：

```
In : for a in dir(future):
...:     if not a.startswith('_'):
...:         print(a)
...:
add_done_callback
cancel
cancelled
done
exception
get_loop
remove_done_callback
result
set_exception
set_result
```

### Task
Eventloop除了支持协程，还支持注册Future和Task2种类型的对象，那为什么要存在Future和Task这2种类型呢？

先回忆前面的例子，Future是协程的封装，Future对象提供了很多任务方法(如完成后的回调、取消、设置任务结果等等)，但是开发者并不需要直接操作Future这种底层对象，而是用Future的子类Task协同的调度协程以实现并发。

```py
# 或者用task = loop.create_task(a())
In : task = asyncio.ensure_future(a())

In : task
Out: <Task pending coro=<a() running at /Users/dongwm/mp/2019-05-22/coro1.py:4>>

In : task.done()
Out: False

In : await task
Suspending a
Resuming a

In : task
Out: <Task finished coro=<a() done, defined at /Users/dongwm/mp/2019-05-22/coro1.py:4> result=None>

In : task.done()
Out: True
```

## asyncio 正确使用

1. async函数本身不会并发。调用async函数会顺序执行。除非一组并行执行的async函数中有一部分**被await协程阻塞**了。
2. 强烈注意。即是await堵塞可以导致进程间切换。但如果**await占用的资源加锁**，不支持多协程访问，同样会导致，切换到其他线程的时候，堵塞在锁上。



### asyncio.create_task()/asyncio.ensure_future()

* 创建**task和future**，不执行内容，只创建待执行的task和future。
* 配合**await关键字可以并发执行**
```py
async def c3():
    task1 = asyncio.create_task(a())
    task2 = asyncio.create_task(b())
    await task1
    await task2
```

### asyncio.gather()

* gather多个**异步函数**可以**并发执行**
* asyncio.gather 会创建 2 个子任务，当出现 await 的时候，程序会在这 2 个子任务之间进行调度。


```
async def c1():
    await asyncio.gather(a(), b())
```

### asyncio.wait()

* wait()多个**异步task或异步函数**构成的**列表**，可以**并发执行**

```
await asyncio.wait([a(), b()])
```

### asyncio.run()

* 堵塞执行一个异步任务直到结束
* **同步执行。不能并发**
```
asyncio.run(main())
```
